services:
  nginx:
    image: nginx:alpine
    container_name: vllm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - vllm-salamandra
      - vllm-alia
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  vllm-salamandra:
    image: vllm/vllm-openai:v0.10.2
    container_name: vllm-salamandra
    expose:
      - "8000"
    volumes:
      - ./hf_cache:/root/.cache/huggingface
    environment:
      - VLLM_API_KEY=${VLLM_API_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    command: >
      --model BSC-LT/salamandra-7b-instruct-tools-16k
      --host 0.0.0.0
      --port 8000
      --api-key ${VLLM_API_KEY}
      --gpu-memory-utilization 0.9
      --max-model-len 16384
      --dtype auto
      --tensor-parallel-size 4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3']
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vllm-alia:
    image: vllm/vllm-openai:v0.10.2
    container_name: vllm-alia
    expose:
      - "8001"
    volumes:
      - ./hf_cache:/root/.cache/huggingface
    environment:
      - VLLM_API_KEY=${VLLM_API_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    command: >
      --model /root/.cache/huggingface/ALIA-40b-instruct_Q8_0/ALIA-40b-instruct_bos_Q8_0.gguf
      --host 0.0.0.0
      --port 8001
      --api-key ${VLLM_API_KEY}
      --gpu-memory-utilization 0.9
      --max-model-len 8192
      --dtype auto
      --tensor-parallel-size 4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['4', '5', '6', '7']
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

