services:
  nginx:
    image: nginx:alpine
    container_name: vllm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - vllm-apertus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  vllm-apertus:
    image: ghcr.io/forpublicai/vllm-apertus
    container_name: vllm-apertus
    expose:
      - "8000"
    volumes:
      - ./hf_cache:/root/.cache/huggingface
    environment:
      - VLLM_API_KEY=${VLLM_API_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    command: >
      --model swiss-ai/Apertus-70B-Instruct-2509
      --host 0.0.0.0
      --port 8000
      --api-key ${VLLM_API_KEY}
      --gpu-memory-utilization 0.8
      --max-model-len 8192
      --dtype auto
      --tensor-parallel-size 8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

